export * from './ComoComprar';
export * from './Contacto';
export { default as Detalle } from './Detalle/Detalle';
export * from './Devoluciones';
export { default as Home } from './Home/Home';
export * from './LandingPage/components';
export * from './LandingPage';
export * from './LandingPage/view';
export * from './Search';
export * from './Talles';
